export const PROJECTILES = {
  mizrak: {
    name: "Mızrak",
    type: "Akıllı Dolanan Mühimmat",
    manufacturer: "BAYKAR",
    damage: 65,
    speed: 280,
    explosionRadius: 75,
    homing: true,
    turnSpeed: 100,
    width: 36,
    height: 12,
    health: 1,
    behavior: "Havada süzülerek en yüksek cana sahip düşman kara aracına kilitlenir ve çarptığında büyük bir patlama alanı yaratır.",
    icon: "🚀",
    cost: 0,
    category: "WEAPON"
  },
  sivrisinek: {
    name: "Sivrisinek",
    type: "Akıllı Dolanan Mühimmat",
    manufacturer: "BAYKAR",
    damage: 80,
    speed: 280,
    explosionRadius: 90,
    homing: true,
    turnSpeed: 180,
    width: 32,
    height: 8,
    health: 1,
    swarmCount: 15,
    physDamage: 6,
    physSpeed: 200,
    physTurnSpeed: 180,
    physExplosionRadius: 35,
    behavior: "Kıvrak akıllı mühimmattır. En yakındaki düşman kara aracına kilitlenerek yüksek manevra kabiliyetiyle dalar.",
    icon: "🦟",
    cost: 60,
    category: "WEAPON"
  },
  mam_l: {
    name: "MAM-L",
    type: "Mini Akıllı Mühimmat",
    manufacturer: "ROKETSAN",
    damage: 95,
    speed: 330,
    explosionRadius: 60,
    homing: true,
    turnSpeed: 140,
    width: 10,
    height: 4,
    health: 1,
    bypassArmor: true,
    behavior: "Süzülerek rakibe kilitlenir. Zırh delici başlığı sayesinde zırhı yok sayarak doğrudan cana hasar vurur.",
    icon: "🔥",
    cost: 90,
    category: "WEAPON"
  },
  mam_t: {
    name: "MAM-T",
    type: "Akıllı Mühimmat",
    manufacturer: "ROKETSAN",
    damage: 100,
    speed: 310,
    explosionRadius: 120,
    homing: true,
    turnSpeed: 105,
    width: 14,
    height: 5,
    health: 1,
    behavior: "Lazer arayıcı başlıklı mühimmattır. Geniş bir alandaki tüm düşmanlara ağır hasar verir.",
    icon: "💣",
    cost: 120,
    category: "WEAPON"
  },
  kemankes_1: {
    name: "KEMANKEŞ 1",
    type: "Mini Seyir Füzesi",
    manufacturer: "BAYKAR",
    damage: 130,
    speed: 390,
    explosionRadius: 80,
    homing: true,
    turnSpeed: 130,
    width: 17,
    height: 6,
    health: 1,
    behavior: "Aşırı hızlı jet motorlu mini seyir füzesidir. Dar ama derin hasar verir.",
    icon: "🎯",
    cost: 150,
    category: "WEAPON"
  },
  kemankes_2: {
    name: "KEMANKEŞ 2",
    type: "Mini Seyir Füzesi",
    manufacturer: "BAYKAR",
    damage: 180,
    speed: 370,
    explosionRadius: 100,
    homing: true,
    turnSpeed: 115,
    width: 25,
    height: 8,
    health: 2,
    behavior: "Jet motorlu mini seyir füzesidir. Devasa hızıyla hedefe saniyeler içinde ulaşır ve kritik hasar verir.",
    icon: "💘",
    cost: 180,
    category: "WEAPON"
  },
  cakir: {
    name: "ÇAKIR",
    type: "Seyir Füzesi",
    manufacturer: "ROKETSAN",
    damage: 220,
    speed: 480,
    explosionRadius: 180,
    homing: true,
    turnSpeed: 65,
    width: 41,
    height: 6,
    health: 3,
    behavior: "Radar soğurucu gövdeye sahip turbojet motorlu seyir füzesidir. Aşırı ağır hasar verir.",
    icon: "⚡",
    cost: 220,
    category: "WEAPON"
  },
  mini_iha: {
    name: "Mini İHA",
    type: "Mini Robot İHA",
    manufacturer: "BAYKAR",
    damage: 0,
    speed: 120,
    explosionRadius: 0,
    homing: false,
    turnSpeed: 0,
    width: 22,
    height: 5,
    health: 2,
    behavior: "En yakın düşmanın üstünde döner; 4 saniye boyunca onun kontrol tuşlarını tersine çevirerek yavaşlatır.",
    icon: "🛩️",
    cost: 75,
    category: "SUPPORT"
  },
  kalkan_diha: {
    name: "KALKAN DİHA",
    type: "Gözetleme DİHA'sı",
    manufacturer: "BAYKAR",
    damage: 0,
    speed: 180,
    explosionRadius: 0,
    homing: false,
    turnSpeed: 0,
    width: 32,
    height: 8,
    health: 5,
    behavior: "Dikey kalkış yapar. 10 saniye boyunca zırh yeniler.",
    icon: "🛡️",
    cost: 100,
    category: "SUPPORT"
  },
  fettah: {
    name: "FETTAH",
    type: "Hipersonik Füze",
    manufacturer: "ROKETSAN",
    damage: 250,
    speed: 620,
    explosionRadius: 160,
    homing: true,
    turnSpeed: 50,
    width: 55,
    height: 8,
    health: 1,
    behavior: "Katı yakıtlı hipersonik füzedir. İnanılmaz hızı ve yıkıcı patlama etkisiyle hedefleri anında kül eder.",
    icon: "💘",
    cost: 250,
    category: "WEAPON"
  },
  fettah_2: {
    name: "FETTAH 2",
    type: "Gelişmiş Hipersonik Füze",
    manufacturer: "ROKETSAN",
    damage: 300,
    speed: 680,
    explosionRadius: 200,
    homing: true,
    turnSpeed: 45,
    width: 60,
    height: 9,
    health: 2,
    behavior: "Aero-balistik manevra kabiliyetine sahip ikinci nesil hipersonik füzedir. Durdurulamaz hızda devasa hasar verir.",
    icon: "💘",
    cost: 300,
    category: "WEAPON"
  },
  ebabil: {
    name: "EBABİL",
    type: "MIRV Balistik Füze",
    manufacturer: "GIDS",
    damage: 200,
    speed: 750,
    explosionRadius: 250,
    homing: true,
    turnSpeed: 30,
    width: 80,
    height: 12,
    health: 4,
    behavior: "MIRV harp başlığı taşıyan orta menzilli balistik füzedir. Düşmana yönelen en yıkıcı ve en ağır silahtır.",
    icon: "💘",
    cost: 350,
    category: "WEAPON"
  }
};
