export const PROJECTILES = {
  mizrak: {
    name: "Mızrak",
    type: "Akıllı Dolanan Mühimmat",
    manufacturer: "BAYKAR",
    damage: 120,
    speed: 350,
    explosionRadius: 150,
    homing: true,
    turnSpeed: 120,
    width: 36,
    height: 12,
    health: 1,
    behavior: "Yerden toplandığında roket desteğiyle (RATO) fırlatılır. Havada süzülerek en yüksek cana sahip düşman kara aracına kilitlenir, ona doğru süzülür ve çarptığında büyük bir patlama alanı yaratır.",
    icon: "🚀",
    cost: 0,
    category: "WEAPON"
  },
  sivrisinek: {
    name: "Sivrisinek",
    type: "Akıllı Dolanan Mühimmat",
    manufacturer: "BAYKAR",
    damage: 70,
    speed: 420,
    explosionRadius: 90,
    homing: true,
    turnSpeed: 180,
    width: 32,
    height: 8,
    health: 1,
    swarmCount: 15,
    physDamage: 6,
    physSpeed: 200,
    physTurnSpeed: 180,
    physExplosionRadius: 35,
    behavior: "Yerden toplandığında katapulttan hızla fırlatılır. Mızrak'a kıyasla çok daha hafif ve kıvraktır. En yakındaki düşman kara aracına kilitlenerek yüksek manevra kabiliyetiyle dalar ve çarptığında orta büyüklükte bir hasar alanı oluşturur.",
    icon: "🦟",
    cost: 60,
    category: "WEAPON"
  },
  mam_l: {
    name: "MAM-L",
    type: "Mini Akıllı Mühimmat",
    manufacturer: "ROKETSAN",
    damage: 85,
    speed: 300,
    explosionRadius: 60,
    homing: true,
    turnSpeed: 100,
    width: 10,
    height: 4,
    health: 1,
    bypassArmor: true,
    behavior: "Mini akıllı mühimmattır. Süzülerek en yakındaki rakibe kilitlenir. Patlama yarıçapı küçüktür ancak zırh delici başlığı sayesinde rakibin zırh değerini yok sayarak doğrudan canına (HP) hasar vurur.",
    icon: "🔥",
    cost: 90,
    category: "WEAPON"
  },
  mam_t: {
    name: "MAM-T",
    type: "Akıllı Mühimmat",
    manufacturer: "ROKETSAN",
    damage: 100,
    speed: 280,
    explosionRadius: 120,
    homing: true,
    turnSpeed: 70,
    width: 14,
    height: 5,
    health: 1,
    behavior: "Lazer arayıcı başlıklı akıllı süzülen mühimmattır. Hızı nispeten düşüktür ancak parçacık etkili devasa harp başlığı sayesinde geniş bir alandaki tüm düşmanlara ağır hasar verir.",
    icon: "💣",
    cost: 120,
    category: "WEAPON"
  },
  kemankes_1: {
    name: "KEMANKEŞ 1",
    type: "Mini Akıllı Seyir Füzesi",
    manufacturer: "BAYKAR",
    damage: 130,
    speed: 520,
    explosionRadius: 80,
    homing: true,
    turnSpeed: 100,
    width: 17,
    height: 6,
    health: 1,
    behavior: "Daha hafif ve havadan fırlatılan jet motorlu mini seyir füzesidir. Aşırı hızlıdır, dar ama derin hasar verir.",
    icon: "🎯",
    cost: 150,
    category: "WEAPON"
  },
  kemankes_2: {
    name: "KEMANKEŞ 2",
    type: "Mini Akıllı Seyir Füzesi",
    manufacturer: "BAYKAR",
    damage: 180,
    speed: 500,
    explosionRadius: 100,
    homing: true,
    turnSpeed: 90,
    width: 25,
    height: 8,
    health: 1,
    behavior: "Jet motorlu mini seyir füzesidir. Roket destekli kalkışla (RATO) fırlatılır. Devasa hızıyla hedefe saniyeler içinde ulaşır ve kritik hasar (180) verir.",
    icon: "💘",
    cost: 180,
    category: "WEAPON"
  },
  cakir: {
    name: "ÇAKIR",
    type: "Seyir Füzesi",
    manufacturer: "ROKETSAN",
    damage: 220,
    speed: 480,
    explosionRadius: 180,
    homing: true,
    turnSpeed: 60,
    width: 41,
    height: 6,
    health: 3,
    behavior: "Turbojet motorlu stratejik seyir füzesidir. Radar soğurucu gövdesi sayesinde düşman savunmaları tarafından vurulması çok zordur (3 Can). Su sathına yakın (sea-skimming) uçar ve çarpışmada 220 hasar vererek devasa bir alanı yok eder.",
    icon: "⚡",
    cost: 220,
    category: "WEAPON"
  },
  mini_iha: {
    name: "Bayraktar Mini İHA",
    type: "Mini Robot İnsansız Hava Aracı",
    manufacturer: "BAYKAR",
    damage: 0,
    speed: 120,
    explosionRadius: 0,
    homing: false,
    turnSpeed: 0,
    width: 22,
    height: 5,
    health: 2,
    behavior: "El ile fırlatılan hafif gözetleme dronudur. Fırlatıldığında en yakın düşmanın üzerinde dönmeye başlar ve 10 saniye boyunca o düşmanın kontrol tuşlarını tersine çevirerek onu yavaşlatır.",
    icon: "🛩️",
    cost: 75,
    category: "SUPPORT"
  },
  kalkan_diha: {
    name: "KALKAN DİHA",
    type: "Dikey İniş Kalkışlı İnsansız Hava Aracı",
    manufacturer: "BAYKAR",
    damage: 0,
    speed: 180,
    explosionRadius: 0,
    homing: false,
    turnSpeed: 0,
    width: 32,
    height: 8,
    health: 5,
    behavior: "Dikey kalkış yapan gözetleme DİHA'sıdır. Kullanıcının üzerinde sabit kalarak 15 saniye boyunca çevredeki tüm düşmanların konumlarını açığa çıkarır (duvar arkası dahil) ve oyuncunun zırhını yeniler.",
    icon: "🛡️",
    cost: 100,
    category: "SUPPORT"
  },
  fettah: {
    name: "FETTAH",
    type: "Hipersonik Füze",
    manufacturer: "ROKETSAN",
    damage: 250,
    speed: 600,
    explosionRadius: 160,
    homing: true,
    turnSpeed: 80,
    width: 55,
    height: 8,
    health: 1,
    behavior: "Katı yakıtlı hipersonik füzedir. İnanılmaz hızı ve yıkıcı patlama etkisiyle hedefleri anında kül eder.",
    icon: "💘",
    cost: 250,
    category: "WEAPON"
  },
  fettah_2: {
    name: "FETTAH 2",
    type: "Gelişmiş Hipersonik Füze",
    manufacturer: "ROKETSAN",
    damage: 300,
    speed: 650,
    explosionRadius: 200,
    homing: true,
    turnSpeed: 70,
    width: 60,
    height: 9,
    health: 2,
    behavior: "Aero-balistik manevra kabiliyetine sahip ikinci nesil hipersonik füzedir. Durdurulamaz hızda devasa hasar verir.",
    icon: "💘",
    cost: 300,
    category: "WEAPON"
  },
  ebabil: {
    name: "Ebabil",
    type: "MIRV Balistik Füze",
    manufacturer: "GIDS",
    damage: 350,
    speed: 700,
    explosionRadius: 250,
    homing: true,
    turnSpeed: 50,
    width: 80,
    height: 12,
    health: 3,
    behavior: "MIRV harp başlığı taşıyan orta menzilli balistik füzedir. Düşmana yönelen en yıkıcı ve en ağır silahtır.",
    icon: "💘",
    cost: 350,
    category: "WEAPON"
  }
};
